

const GET_FOLLOWERS = 'profile/GET_FOLLOWERS';
const GET_BOOKMARKS = 'profile/GET_BOOKMARKS';
const GET_OTHERUSER = 'profile/GET_OTHERUSER';
const CREATE_FOLLOWER = 'profile/CREATE_FOLLOWER';
const GET_ALLFOLLOWERS = 'profile/GET_ALLFOLLOWERS';



export {
  GET_FOLLOWERS,
  GET_BOOKMARKS,
  GET_OTHERUSER,
  CREATE_FOLLOWER,
  GET_ALLFOLLOWERS,


}
