



const GET_SPECIFIC_STORY = 'story/GET_SPECIFIC_STORY';
const GET_ALLSTORIES = 'story/GET_ALLSTORIES';
const CREATE_STORY = 'story/CREATE_STORY';
const DELETE_STORY = 'story/DELETE_STORY';



export {
  GET_SPECIFIC_STORY,
  GET_ALLSTORIES,
  CREATE_STORY,
  DELETE_STORY,


}
